### ISSUE TITLE
Timeout refactoring broke drivers

### ISSUE THREAD

**Issue by wieset** [rock-core/drivers-iodrivers_base#29] opened 2019-10-02 16:13 UTC
Merged pull request #28 broke packages

- rock-drivers/drivers-imu_stim300
- esa-prl/drivers-temperature
- esa-prl/drivers-dsp1760

throwing errors in call to readPacket()

rock-drivers/drivers-imu_stim300:
```
TimeoutError buffer size: 0
```

 esa-prl/drivers-temperature:
```
FileDescriptorActivity: error in select(), errno = 9
```

esa-prl/drivers-dsp1760:
```
FileDescriptorActivity: timeout in select()
```

**Comment by doudou** [comment] 2019-10-03 12:27
Hi Tim. Sorry to hear that.

The two esa-prl messages are not related to `iodrivers_base` (i.e. they are not the "right" messages, I am guessing that the "right" messages are somewhere else in the file). These usually happen because of a misuse of `iodrivers_base::Task` or, if you're not using it, of forgetting to remove closed file descriptors from the FileDescriptorActivity.

The `imu_stim300` message is indeed caused by a timeout, but it unfortunately is not very informative (to say the least). It would be very useful if you would display `e.what()` in the error message, which would tell us what part of the timeout logic is triggering.

Generally speaking, if you could attach a debugger and check where in the timeout logic this happens, it would be very helpful.

**Comment by wieset** [comment] 2019-10-03 16:21
Hi Sylvain, thanks for your suggestions. I added catching of TimeoutErrors to our drivers and e.what() is the same for all three packages:

```
readPacket(): no data after waiting 0ms
```

The calls are

```
readPacket(buffer, MAX_PACKET_SIZE, base::Time::fromSeconds(0.1));
readPacket(buffer, MAX_PACKET_SIZE, 1000, 1000);
readPacket(buffer, MAX_PACKET_SIZE, 2000, 2000);
```

Any idea what could cause this? I will pick this up when I am back from vacation.

**Comment by wieset** [comment] 2019-10-03 16:54
Actually it looks like we are still reading data successfully. Only now, `readPacket()` is throwing these TimeoutErrors every couple of calls, which it didn't do before.

**Comment by doudou** [comment] 2019-10-07 16:44
Sorry for the long delay, @wieset. 

From the error, it seems that you hit https://github.com/rock-core/drivers-iodrivers_base/blob/master/src/Driver.cpp#L820 with `now == start_time` (within one milliseconds). Which should be only possible if `first_byte_timeout` is zero. And I don't see how that could happen by just reading the code.

Could you run your code with a breakpoint on this line ? And inspect the value of the different timeouts, as well as the initial callsite. I'm sorry to ask this of you... You would need first to delete the `<tags>stable</tags>` line from iodrivers_base's `manifest.xml` and recompile it to get debug symbols.

**Comment by doudou** [comment] 2019-10-17 12:39
Hi @wieset 

This problem should be fixed by #30. Could you test it ?

I am very sorry, I thought the timeout logic in readPacket was properly unit-tested, but
it wasn't, and I got lucky (or, rather, unlucky) when I tested it on a device here.

**Closed** 2019-10-18 11:59 UTC

**Comment by wieset** [comment] 2019-10-20 21:36
Hi Sylvain,

Thanks for the update and great you found a fix! Will test it in a week when I am back at work.

**Comment by wieset** [comment] 2019-10-29 10:07
Tested it today and looks like everything is back in working order.
